apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: connect
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: connect
            image: gesselsam96/postgress-py:1.8
          restartPolicy: OnFailure